
<?php

$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>




<?php echo $this->formHidden($form->get('id')); ?>

<label><?php echo $this->translate("Monday"); ?></label>
<?php $monday = $form->get('monday'); ?>
<?php echo $this->formRow($monday->get('dayOfWeek')); ?>
<?php echo $this->partial("form/element",array("element" => $monday->get('dayOfWeek'))); ?>

<?php echo $this->partial("form/element",array("element" => $monday->get('startTime'))); ?>
<?php echo $this->partial("form/element",array("element" => $monday->get('endTime'))); ?>

<br>
<label><?php echo $this->translate("Tuesday"); ?></label>
<?php $tuesday = $form->get('tuesday'); ?>
<?php echo $this->formRow($tuesday->get('dayOfWeek')); ?>

<?php echo $this->formRow($tuesday->get('startTime')); ?>
<?php echo $this->formRow($tuesday->get('endTime')); ?>

<?PHP
 echo $this->formHidden($form->get('csrf'));
 echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag($form);
?>
