
<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
?>


<div class="row">



    <?php echo $this->formHidden($form->get('id')); ?>


    <?php echo $this->partial("cdi-commons/form/element", array("element" => $this->form->get('name'))); ?>


</div>

<?php foreach ($this->form->getFieldsets() as $fieldset): ?>

    <div class="row">
               <?php echo $this->formHidden($fieldset->get('id')); ?>
           <?php echo $this->formHidden($fieldset->get('calendar')); ?>
        <div class="col-lg-3">
            <label><?php echo $this->translate(ucfirst($fieldset->getName())); ?></label>
             <?php echo $this->partial("cdi-commons/form/element", array("element" => $fieldset->get('dayOfWeek'))); ?>
        </div>   

       
        <div class="col-lg-4">
            <?php echo $this->partial("cdi-commons/form/element", array("element" => $fieldset->get('startTime'))); ?>
        </div>

        <div class="col-lg-4">
            <?php echo $this->partial("cdi-commons/form/element", array("element" => $fieldset->get('endTime'))); ?>
        </div>



    </div>

<?php endforeach; ?>
<?PHP
echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag($form);
?>


