
<div class="row">
    <div class="col-md-12 col-sm-12">

        <div class="portlet portlet-default">

            <div class="portlet-header">
                <h4 class="portlet-title">
                    Calendarios
                </h4>
            </div> <!-- /.portlet-header -->

            <div class="portlet-body">    
                   <?php 
                 
                   echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
                
                
                    <a class="btn btn-primary" href="/cdicalendar/new"><?php echo $this->translate("Agregar nuevo"); ?></a>
                <?php echo $this->RenderCdiGrid($this->grid); ?>


            </div> <!-- /.portlet-body -->

        </div> <!-- /.portlet -->

    </div>
</div>

